Repository ishita-43/Blockchain-Based-Voting-System, pull requests merged in 2024-10, with the labels that each got.

#17 Closes #16: Correcting Voting.sol logic
  contracts/Voting.sol
Labels: level1, wob24

#19 Migrated frontend code to Nextjs
  Foundry_Contracts/README.md
  Foundry_Contracts/script/Deploy.s.sol
  README.md
  build/contracts/Migrations.json
  build/contracts/Voting.json
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/README.md
  frontend/next.config.mjs
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.mjs
  frontend/public/Bhadal-Glacier-Himachal-Pradesh.jpg.crdownload
  frontend/public/Chandra-Glacier-Himachal-Pradesh.jpg.crdownload
  frontend/public/HPQR.fw.png
  frontend/public/emblem.png
  frontend/public/fotor-ai-20240521164131.jpg
  frontend/src/app/Admin/page.tsx
  frontend/src/app/HomePage.tsx
  frontend/src/app/Login/page.tsx
  frontend/src/app/Results/page.tsx
  frontend/src/app/Voting/page.tsx
  frontend/src/app/globals.css
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
  frontend/src/app/voting.js
  frontend/src/components/Footer.tsx
  frontend/src/components/Header.tsx
  frontend/tailwind.config.ts
  frontend/tsconfig.json
  interact.js
  src/index.html
  src/style/style.css
  src/submit_vote.php
  src/voting.html
Labels: level3, wob24

#21 Enhanced the code for gas optimization
  Foundry_Contracts/src/Voting.sol
Labels: level1, wob24

#23 feat: prevent duplicate voter authorization and ensure candidate name…
  Foundry_Contracts/src/Voting.sol
Labels: level1, wob24

#25 feat: add functionality to end election
  Foundry_Contracts/src/Voting.sol
Labels: level1, wob24

#27 add: reject ether functionality
  Foundry_Contracts/src/Voting.sol
Labels: level1, wob24

#30 Optimize Gas Efficiency in Voting Contract
  Foundry_Contracts/src/Voting.sol
Labels: level1, wob24

#31 Update Voting.sol
  Foundry_Contracts/src/Voting.sol
Labels: wob24
